#include <EEPROM.h>

#define BLOCK_SIZE 32
#define SSID_LOCATION 0x00
#define PASSWORD_LOCATION 0x20
#define LAST_MATRIX_BRIGHTNESS_LOCATION 0x40
#define LAST_SEG_DISPLAY_BRIGHTNESS_LOCATION 0x60
#define EEPROM_INITALIZED_LOCATION 0x80
